# Generated by Django 6.1.2 on 2026-10-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Exemplo: VL-01, VL-02, VC-01', max_length=10, unique=True, verbose_name='Código do Veículo')),
                ('modelo', models.CharField(help_text='Exemplo: Fiat Cronos, Renault Master, etc.', max_length=60, verbose_name='Modelo / Descrição')),
                ('placa', models.CharField(blank=True, help_text='Exemplo: BRA2E19', max_length=10, verbose_name='Placa do Veículo')),
                ('categoria', models.CharField(choices=[('LEVE', 'Veículo Leve (Até 4 passageiros)'), ('COLETIVO', 'Veículo Coletivo (Até 18 passageiros)')], default='LEVE', max_length=10, verbose_name='Categoria')),
                ('capacidade', models.PositiveIntegerField(help_text='Número máximo de passageiros permitidos (4 ou 18)', verbose_name='Capacidade de Passageiros')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o veículo está apto para receber novas reservas', verbose_name='Ativo na Frota')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Nome completo ou matrícula do colaborador', max_length=100, verbose_name='Identificação do Solicitante')),
                ('setor', models.CharField(help_text='Setor solicitante (ex: Operações, Manutenção, Administrativo, TI)', max_length=80, verbose_name='Setor do Porto')),
                ('atividade', models.CharField(help_text='Exemplo: Reunião administrativa, Inspeção técnica, Treinamento, Visita externa', max_length=120, verbose_name='Finalidade / Atividade')),
                ('origem', models.CharField(help_text='Ponto de partida do deslocamento', max_length=120, verbose_name='Local de Origem')),
                ('destino', models.CharField(help_text='Destino final da atividade', max_length=120, verbose_name='Local de Destino')),
                ('data', models.DateField(help_text='Data do deslocamento (não pode ser anterior à data de hoje)', verbose_name='Data da Reserva')),
                ('horario_saida', models.TimeField(help_text='Horário previsto para o início da viagem', verbose_name='Horário de Saída')),
                ('horario_retorno', models.TimeField(help_text='Horário previsto para o término da viagem (deve ser posterior à saída)', verbose_name='Horário de Retorno')),
                ('quantidade_passageiros', models.PositiveIntegerField(help_text='Total de pessoas que serão transportadas (máximo 18 no sistema)', verbose_name='Quantidade de Passageiros')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais relevantes para o motorista ou COSEG', null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=15, verbose_name='Status da Reserva')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Registro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.veiculo', verbose_name='Veículo Solicitado')),
            ],
            options={
                'verbose_name': 'Reserva de Veículo',
                'verbose_name_plural': 'Reservas de Veículos',
                'ordering': ['-data', 'horario_saida'],
            },
        ),
    ]
